### ISSUE TITLE
yarn: There are no scenarios

### ISSUE THREAD

**Issue by hackerb9** [jerch/xterm-addon-image#2]
Running bootstrap.sh seems to setup the repository correctly, but then just ends with an error message from `yarn`. 

```
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.
```

I have never used xterm.js. How does one launch it?

**Comment by jerch** [comment]
Ive never seen that error message, so I am not quite sure what it means. Looking at SO indicates, that you most likely have an outdated yarn installed. You can either update your global yarn (how depends on how it got installed in the first place), or try to use `npm install` instead:

```bash
git clone --depth 1 --branch 4.16.0 https://github.com/xtermjs/xterm.js.git
cd xterm.js
rm -rf .git
cd addons
git clone https://github.com/jerch/xterm-addon-image
cd ..
cp -avx addons/xterm-addon-image/overwrite/* .
# for npm install we have to patch typescript version
sed -i 's/"typescript": "^4.4.4"/"typescript": "4.4.4"/g' package.json
npm install
```

If that all succeeds you can start playing around with it (run these commands from base repo folder):
- `yarn start` or `npm start` to get the demo running (point browser to localhost:3000)
- `yarn test-api` or `npm run test-api` for addon tests
- `yarn watch` or `npm run watch` to run the TS compiler in watch mode (helpful if you want to make source changes)

And to build the final addon bundles:
```bash
cd addons/xterm-addon-image
yarn package   # or npm run package
```
which creates the browser bundles under `addons/xterm-addon-image/lib`. 

I admit that this tight integration with the base repo is subpar, but it is currently the only way to pull the symbols correctly for the tests and the demo. If I find the time I might further detangle it. Further note that the base repo demo still lacks proper flow control (we discussed that already in the PR thread), thus will stop working for fast succession of big images (see console.log if the demo behaves weird).

If thats still failing, just ping me back.

**Comment by jerch** [comment]
@hackerb9 Just release an npm version, maybe thats easier to play with. Gonna close the issue, feel free to reopen if something is still missing.
