### ISSUE TITLE
Don't use : characters in file names

### ISSUE THREAD

**Issue by Tyriar** [jerch/xterm-addon-image#52]
This file breaks checkout on WIndows: https://github.com/jerch/xterm-addon-image/blob/master/fixture/testimages/sixel%3A-

![image](https://github.com/jerch/xterm-addon-image/assets/2193314/fb18b90f-52e5-4213-b1e1-775b65a03769)

**Comment by jerch** [comment]
@Tyriar Eww - no clue how this happened, must have been the cat. Looks like a sloppy file commit, as it contains other files that should not be in the repo :smile_cat:

**Comment by Tyriar** [comment]
I was a little taken aback when I saw the error from git, never seen that before 🙂
