### ISSUE TITLE
Positioning breaks

### ISSUE THREAD

**Issue by Tyriar** [jerch/xterm-addon-image#53]
This issue with the scroll bar happens due to the image canvas https://github.com/microsoft/vscode/issues/184894

![image](https://github.com/jerch/xterm-addon-image/assets/2193314/285407fa-6d73-4fcd-a1ed-1c2b8a838c40)

No errors in console, it just happens sometimes. I notice the canvas isn't getting resized with the others:

![Recording 2023-06-26 at 13 04 19](https://github.com/jerch/xterm-addon-image/assets/2193314/66208b0f-67da-462d-98ad-f17fd8a3065f)

**Comment by jerch** [comment]
Hmm, seems to be a to eager optimization exiting the render method too early, this call needs to be before all the early exit clauses: https://github.com/jerch/xterm-addon-image/blob/f2299bda4f8ed3eefffe15fd913e928e8b05b0cd/src/ImageStorage.ts#L357

**Comment by jerch** [comment]
The change in #54 should fix it, gonna do a patch release so you test it.

Also about canvas resizes - found it the issue I had before with it. `onResize` gets called before the output system has adjusted the metrics, thus I could not use that event for canvas adjustments (I only use it for terminal buffer adjustments). Instead the `render` method does it on the fly if needed, but skipped it wrongly before, if there was no image data to draw at all.

**Comment by Tyriar** [comment]
Thanks for the quick fix!
