### ISSUE TITLE
Switch to @xterm/xterm

### ISSUE THREAD

**Issue by link2xt** [jerch/xterm-addon-image#59]
`xterm` is deprecated.

**Comment by link2xt** [comment]
Or rather readme should be fixed to say `npm install --save @xterm/addon-image` instead of `npm install --save xterm-addon-image`

**Comment by link2xt** [comment]
Sorry for the noise, it seems addon is moved to the main repo

Maybe this repo should be archived?

**Comment by jerch** [comment]
It is not yet archived because of PRs, that are conceptual testbeds for various features.
